/**
*
*Copyright 2010 OuterCurve Foundation
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
/**
* Defines default Data Service URL for this proxy class
*/
#define DEFAULT_SERVICE_URL @""


#define DataServiceVersion @"2.0"

#import "ODataObject.h"
#import "ObjectContext.h"
#import "DataServiceQuery.h"
#import "ODataGUID.h"
#import "ODataBool.h"
#import  "mProperties.h"


/**
 * @interface:District
 * @Type:EntityType
 
 * @key:id* 
 */
@interface NorthwindModel_District : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_understand;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_name;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_id;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_District_City
	* @FromRole:District
	* @ToRole:City
	*/
	NSMutableArray *m_city;
	
}

@property ( nonatomic , retain , getter=getunderstand , setter=setunderstand: ) NSString *m_understand;
@property ( nonatomic , retain , getter=getname , setter=setname: ) NSString *m_name;
@property ( nonatomic , retain , getter=getid , setter=setid: )NSNumber *m_id;
@property ( nonatomic , retain , getter=getcity , setter=setcity: )NSMutableArray *m_city;

+ (id) CreateDistrict;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:See
 * @Type:EntityType
 
 * @key:id* 
 */
@interface NorthwindModel_See : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_id;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:255
	* @FixedLength:
	*/
	NSString *m_placeName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_intro;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_See_City
	* @FromRole:See
	* @ToRole:City
	*/
	NSMutableArray *m_city;
	
}

@property ( nonatomic , retain , getter=getid , setter=setid: )NSNumber *m_id;
@property ( nonatomic , retain , getter=getplaceName , setter=setplaceName: ) NSString *m_placeName;
@property ( nonatomic , retain , getter=getintro , setter=setintro: ) NSString *m_intro;
@property ( nonatomic , retain , getter=getcity , setter=setcity: )NSMutableArray *m_city;

+ (id) CreateSee;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:City
 * @Type:EntityType
 
 * @key:id* 
 */
@interface NorthwindModel_City : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_url;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_id;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_name;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_location;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_See_City
	* @FromRole:City
	* @ToRole:See
	*/
	NSMutableArray *m_sees;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Understand_City
	* @FromRole:City
	* @ToRole:Understand
	*/
	NSMutableArray *m_understands;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Play_City
	* @FromRole:City
	* @ToRole:Play
	*/
	NSMutableArray *m_plays;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_District_City
	* @FromRole:City
	* @ToRole:District
	*/
	NSMutableArray *m_districts;
	
}

@property ( nonatomic , retain , getter=geturl , setter=seturl: ) NSString *m_url;
@property ( nonatomic , retain , getter=getid , setter=setid: )NSNumber *m_id;
@property ( nonatomic , retain , getter=getname , setter=setname: ) NSString *m_name;
@property ( nonatomic , retain , getter=getlocation , setter=setlocation: ) NSString *m_location;
@property ( nonatomic , retain , getter=getsees , setter=setsees: )NSMutableArray *m_sees;
@property ( nonatomic , retain , getter=getunderstands , setter=setunderstands: )NSMutableArray *m_understands;
@property ( nonatomic , retain , getter=getplays , setter=setplays: )NSMutableArray *m_plays;
@property ( nonatomic , retain , getter=getdistricts , setter=setdistricts: )NSMutableArray *m_districts;

+ (id) CreateCity;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Play
 * @Type:EntityType
 
 * @key:id* 
 */
@interface NorthwindModel_Play : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_location;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_explane;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_id;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_tpy;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Play_City
	* @FromRole:Play
	* @ToRole:City
	*/
	NSMutableArray *m_city;
	
}

@property ( nonatomic , retain , getter=getlocation , setter=setlocation: ) NSString *m_location;
@property ( nonatomic , retain , getter=getexplane , setter=setexplane: ) NSString *m_explane;
@property ( nonatomic , retain , getter=getid , setter=setid: )NSNumber *m_id;
@property ( nonatomic , retain , getter=gettpy , setter=settpy: ) NSString *m_tpy;
@property ( nonatomic , retain , getter=getcity , setter=setcity: )NSMutableArray *m_city;

+ (id) CreatePlay;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Understand
 * @Type:EntityType
 
 * @key:id* 
 */
@interface NorthwindModel_Understand : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:255
	* @FixedLength:
	*/
	NSString *m_visitTime;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_id;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_today;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_history;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Understand_City
	* @FromRole:Understand
	* @ToRole:City
	*/
	NSMutableArray *m_city;
	
}

@property ( nonatomic , retain , getter=getvisitTime , setter=setvisitTime: ) NSString *m_visitTime;
@property ( nonatomic , retain , getter=getid , setter=setid: )NSNumber *m_id;
@property ( nonatomic , retain , getter=gettoday , setter=settoday: ) NSString *m_today;
@property ( nonatomic , retain , getter=gethistory , setter=sethistory: ) NSString *m_history;
@property ( nonatomic , retain , getter=getcity , setter=setcity: )NSMutableArray *m_city;

+ (id) CreateUnderstand;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * Container interface NorthwindEntities, Namespace: NorthwindModel
 */
@interface NorthwindEntities : ObjectContext
{
	 NSString *m_OData_etag;
	 DataServiceQuery *m_District;
	 DataServiceQuery *m_See;
	 DataServiceQuery *m_City;
	 DataServiceQuery *m_Play;
	 DataServiceQuery *m_Understand;
	
}

@property ( nonatomic , retain , getter=getEtag , setter=setEtag: )NSString *m_OData_etag;
@property ( nonatomic , retain , getter=getDistrict , setter=setDistrict: ) DataServiceQuery *m_District;
@property ( nonatomic , retain , getter=getSee , setter=setSee: ) DataServiceQuery *m_See;
@property ( nonatomic , retain , getter=getCity , setter=setCity: ) DataServiceQuery *m_City;
@property ( nonatomic , retain , getter=getPlay , setter=setPlay: ) DataServiceQuery *m_Play;
@property ( nonatomic , retain , getter=getUnderstand , setter=setUnderstand: ) DataServiceQuery *m_Understand;

- (id) init;
- (id) initWithUri:(NSString*)anUri credential:(id)acredential;
- (id) district;
- (id) see;
- (id) city;
- (id) play;
- (id) understand;
- (void) addToDistrict:(id)anObject;
- (void) addToSee:(id)anObject;
- (void) addToCity:(id)anObject;
- (void) addToPlay:(id)anObject;
- (void) addToUnderstand:(id)anObject;

@end
